version: "3.9"

services:
    db:
        image: postgres:12
        environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    test:
        build: .
        command: python manage.py test
        environment:
            - ALPHA_VANTAGE_API_KEY=demo
    test-coverage:
        build: .
        command: |
            coverage run --omit='*/venv/*' manage.py test &&
        environment:
            - ALPHA_VANTAGE_API_KEY=demo
    test-lint:
        build: .
        command: python -m black . -t py38 --check
    