apiVersion: v1
kind: Service
metadata:
  labels:
    app: spectrum-block-monolith
  name: spectrum-block-monolith
  namespace: production
spec:
  ports:
  - port: 8000 # External Port
    protocol: TCP
    targetPort: 8000 # Internal Port (of container)
  selector:
    app: spectrum-block-monolith
status:
  loadBalancer: {} # No Load Balancer Exposed