# Generated by Django 3.2.7 on 2021-10-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EquityDataStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=21)),
                ("datetime", models.DateTimeField()),
                (
                    "exchange",
                    models.CharField(
                        choices=[("US", "United States"), ("MY", "Malaysia")],
                        max_length=2,
                    ),
                ),
                ("open", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("close", models.FloatField()),
                ("adjusted_close", models.FloatField()),
                ("volume", models.FloatField()),
            ],
            options={
                "unique_together": {("ticker", "datetime", "exchange")},
            },
        ),
    ]
