# Generated by Django 3.2.7 on 2021-10-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_store", "0001_equity_data_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equitydatastore",
            name="exchange",
            field=models.CharField(
                choices=[("US", "United States"), ("MY", "Malaysia")], max_length=8
            ),
        ),
    ]
