name: Run CI Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.9.0 ]
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Runs tests
      run: |
        docker-compose run test
    
    - name: Runs coverage
      run: |
        docker-compose run test-coverage

    - name: Run Lint
      run: |
        docker-compose run test-lint